import type { CapabilityDescriptor } from './capability-types.js';

const READ_ONLY_SECURITY = {
  defaultSandbox: 'read-only' as const,
  requiredPermissions: [],
};

const WORKSPACE_WRITE_SECURITY = {
  defaultSandbox: 'workspace-write' as const,
  requiredPermissions: ['workspace.write'],
};

export function getBuiltinCapabilities(): CapabilityDescriptor[] {
  return [
    {
      id: 'plan.task',
      name: 'Task Planning',
      description: 'Generate structured task and implementation plans',
      source: 'builtin',
      provider: 'claude',
      preferredProviders: ['claude'],
      runtime: 'typescript',
      entryPoint: 'builtin:plan.task',
      security: READ_ONLY_SECURITY,
      triggers: ['plan', 'architecture', 'break down task'],
      enabled: true,
    },
    {
      id: 'execute.general',
      name: 'General Execution',
      description: 'Execute a general-purpose task in the workspace',
      source: 'builtin',
      provider: 'claude',
      preferredProviders: ['claude', 'codex'],
      runtime: 'typescript',
      entryPoint: 'builtin:execute.general',
      security: WORKSPACE_WRITE_SECURITY,
      triggers: ['execute', 'implement'],
      enabled: true,
    },
    {
      id: 'implement.code',
      name: 'Code Implementation',
      description: 'Implement or modify code in the repository',
      source: 'builtin',
      provider: 'codex',
      preferredProviders: ['codex', 'claude'],
      runtime: 'typescript',
      entryPoint: 'builtin:implement.code',
      security: WORKSPACE_WRITE_SECURITY,
      triggers: ['implementation', 'coding'],
      enabled: true,
    },
    {
      id: 'analyze.code',
      name: 'Code Analysis',
      description: 'Analyze source code and produce engineering guidance',
      source: 'builtin',
      provider: 'codex',
      preferredProviders: ['codex', 'claude'],
      runtime: 'typescript',
      entryPoint: 'builtin:analyze.code',
      security: READ_ONLY_SECURITY,
      triggers: ['analysis', 'code review'],
      enabled: true,
    },
    {
      id: 'analyze.multimodal',
      name: 'Multimodal Analysis',
      description: 'Analyze UI, screenshots, or multimodal inputs',
      source: 'builtin',
      provider: 'gemini',
      preferredProviders: ['gemini', 'claude'],
      runtime: 'typescript',
      entryPoint: 'builtin:analyze.multimodal',
      security: READ_ONLY_SECURITY,
      triggers: ['ui', 'image', 'multimodal'],
      enabled: true,
    },
    {
      id: 'review.changes',
      name: 'Change Review',
      description: 'Review code and workflow outputs for quality and risk',
      source: 'builtin',
      provider: 'claude',
      preferredProviders: ['claude', 'codex'],
      runtime: 'typescript',
      entryPoint: 'builtin:review.changes',
      security: READ_ONLY_SECURITY,
      triggers: ['review', 'audit'],
      enabled: true,
    },
    {
      id: 'synthesize.outputs',
      name: 'Synthesis',
      description: 'Synthesize outputs from multiple prior phases',
      source: 'builtin',
      provider: 'claude',
      preferredProviders: ['claude'],
      runtime: 'typescript',
      entryPoint: 'builtin:synthesize.outputs',
      security: READ_ONLY_SECURITY,
      triggers: ['synthesize', 'summary'],
      enabled: true,
    },
    {
      id: 'audit.security',
      name: 'Security Audit',
      description: 'Audit implementation for security and quality risks',
      source: 'builtin',
      provider: 'claude',
      preferredProviders: ['claude', 'codex'],
      runtime: 'typescript',
      entryPoint: 'builtin:audit.security',
      security: READ_ONLY_SECURITY,
      triggers: ['security', 'audit'],
      enabled: true,
    },
  ];
}
